name: Build and Push to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: _  
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./LightsOn.BlazorApp/Dockerfile
          push: true
          tags: registry.digitalocean.com/lights-on-container-registry/web-app:latest

      - name: Clean up
        if: always()
        run: docker logout registry.digitalocean.com
